### ISSUE TITLE
Upload not successful: Not Found

### ISSUE THREAD

**Issue by Puyodead1** [skx/github-action-publish-binaries#11]
```
Upload URL is https://uploads.github.com/repos/****/*****/releases/null/assets?name=RP-1.0.0.jar
***************************
 upload was not successful.
 Aborting
 HTTP status is 404
**********************************
{"message":"Not Found","request_id":"07C0:7AB7:7EAAC:9C7C6:5DB0885F","documentation_url":"https://developer.github.com/v3"}
##[error]Docker run failed with exit code 1
```

Release ID is null, not sure why

**Comment by skx** [comment]
* I created a new release in my sample-project:
  * https://github.com/skx/upload-test/releases/tag/v0.0.3
* The action ran:
  * https://github.com/skx/upload-test/commit/0e7b6ba535d1e29838644248f363598cebc3fa38/checks?check_suite_id=278208238
* The upload seemed to complete
  * Upload URL is https://uploads.github.com/repos/skx/upload-test/releases/20923738/assets?name=artifact-one

And indeed I see the artifact in the release.

I note that there are *three* actions launched on release, as noted in #10 , two failed, one succeed.  Weird.

Unfortunately I don't have enough details to investigate your report further.  If you could share the log(s), and the workflow file that would help..

**Comment by skx** [comment]
* run1
  * https://github.com/skx/upload-test/runs/272007747
* run2
  * https://github.com/skx/upload-test/runs/272007734
* run3
  * https://github.com/skx/upload-test/runs/272007713

**Comment by Puyodead1** [comment]
Workflow:
```
name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Make Artifact Directory
      run: "mkdir ./artifacts"
    
    - name: Find and Move JARS
      run: "mv `find target -name *.jar -print` ./artifacts"

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@master
      with:
        name: Artifacts
        path: "./artifacts"
     
    - name: Create ZIP
      uses: montudor/action-zip@v0.1.0
      with: 
        args: "zip -r artifacts.zip ./artifacts"   
     
    - name: Draft Release
      uses: toolmantim/release-drafter@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_ }}
        
    - name: Upload artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_ }}
      with:
        args: './artifacts/Skeppy*.jar'
```

Heres a log file: https://pastebin.com/yHNpuDM4
