### ISSUE TITLE
Input releaseId

### ISSUE THREAD

**Issue by No3x** [skx/github-action-publish-binaries#22]
What's the correct way to pass the `releaseId`? I see in the source code that releaseId should be supported but there is no example how to use it. 

I'm using
```yml
  upload_artifacts:
    name: Upload Artifacts
    needs: [create_release]
    runs-on: ubuntu-latest
    steps:
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: '*.bin'
```

Which results in:
```
 Upload the artifacts1s
    GITHUB_TOKEN: ***
##[warning]Unexpected input 'releaseId', valid inputs are ['entryPoint', 'args']
Run skx/github-action-publish-binaries@release-1.3
  with:
    args: *.bin
  env:
    GITHUB_TOKEN: ***
```

**Comment by skx** [comment]
I haven't used this, it was contributed as part of #21 .

But that said it seems like you're passing an `input`, and instead you should pass an `env`.  So I think you'll want:

```
Upload the artifacts1s
    GITHUB_TOKEN: ***
##[warning]Unexpected input 'releaseId', valid inputs are ['entryPoint', 'args']
Run skx/github-action-publish-binaries@release-1.3
  with:
    args: *.bin
  env:
    GITHUB_TOKEN: ***
    RELEASEID: ${{ needs.create_release.outputs.id }}
```

I hope that helps.  Perhaps @wattry will have some comment if not :)

**Comment by No3x** [comment]
Used this:
```yml
Run skx/github-action-publish-binaries@release-1.3
  with:
    args: *.bin
  env:
    GITHUB_TOKEN: ***
    RELEASEID: 28268292
```
The env RELEASEID is set now.
This is my full action:
```
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO
        run: platformio run
  create_release:
    name: Create Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          releaseId: ${{ steps.create_release.outputs.id }}
        with:
          args: '*.bin'
```
The action runs on push instead of release created but I don't think this makes a difference.

**Comment by skx** [comment]
You should see output from the top of the script:

```
if [ -z "${INPUT_RELEASEID}" ]; then

    #
    # Not specified?  Use the one from the payload
    #
    RELEASE_ID=$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH")

    echo "Discovered RELEASE_ID: ${RELEASE_ID}"
else

    #
    # Otherwise use the supplied value.
    #
    RELEASE_ID="${INPUT_RELEASEID}"

    echo "Using supplied RELEASE_ID: ${RELEASE_ID}"
fi
```

Could you share that output?  Should be just before the upload step.  It seems clear that you're getting a null-value, and I'd like to see if that is because the value is not being set, or because it is being ignored.

There's also the other logging:

```


#
# Sanity-check, show our arguments.
#
echo "Arguments : ${INPUT_ARGS}"
echo "Release ID: ${INPUT_RELEASEID}"
```


In your case I see:

```
Upload URL is https://uploads.github.com/repos/
     No3x/pio-release-nofuss-test/releases/null/assets?name=esp8266_logger-0.2.5.bin
```

That `null` should contain the release ID, but obviously does not.

**Comment by No3x** [comment]
> You should see output from the top of the script:

I was looking for this output but can't find it. That made me look at the code and versions again (used release-1.3). Trying with master now.

> That null should contain the release ID, but obviously does not.

Sure, that's obvious.

**Comment by No3x** [comment]
Output with @master prints out messages (that's good). ReleaseId still null (that's bad)

```yml
 - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_RELEASEID: ${{ steps.create_release.outputs.id }}
        with:
          args: '*.bin'
```
```
 Upload the artifacts5s
{"message":"Not Found","request_id":"0400:3E87:403D5A:4D70DB:5F037FA2","documentation_url":"https://developer.github.com/v3"}
Run skx/github-action-publish-binaries@master
/usr/bin/docker run --name d3590ae94f2017451783b9bcf1709b7234_e25b6a --label 3888d3 --workdir /github/workspace --rm -e pythonLocation -e GITHUB_TOKEN -e INPUT_RELEASEID -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/pio-release-nofuss-test/pio-release-nofuss-test":"/github/workspace" 3888d3:590ae94f2017451783b9bcf1709b7234  "*.bin" ""
Arguments : *.bin
Release ID: 
Discovered RELEASE_ID: null
Processing file esp8266_logger-0.2.5.bin
Upload URL is https://uploads.github.com/repos/No3x/pio-release-nofuss-test/releases/null/assets?name=esp8266_logger-0.2.5.bin
***************************
 upload was not successful.
 Aborting
 HTTP status is 404
**********************************
{"message":"Not Found","request_id":"0400:3E87:403D5A:4D70DB:5F037FA2","documentation_url":"https://developer.github.com/v3"}
```

**Comment by skx** [comment]
I wonder if this is a different issue, perhaps the output step is broken/failing?

If you were to try explicitly setting a value, does that appear in the logging?

```
          releaseId: 28269075
```

Otherwise I'll need to go back to the documentation and compare what I have for `inputs` with other actions:

* https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
  * Seems to match what I've done declaring an `input` with name `releaseId`.

**Comment by No3x** [comment]
Output step seems fine to me with latest posted full workflow. 
Did some testing:
#### 👎  `@master` env RELEASEID: "28269075"
Used this:
```yml
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASEID: "28269075"
        with:
          args: '*.bin'
```
Output:
```
Arguments : *.bin
Release ID: 
Discovered RELEASE_ID: null
```
####  👎  `@master` env RELEASEID: 28269075
Used this:
```yml
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASEID: 28269075
        with:
          args: '*.bin'
```
Output:
```
Arguments : *.bin
Release ID: 
Discovered RELEASE_ID: null
```
#### 👎  `@master` env releaseId: 28269075
Used this:
```yml
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          releaseId: 28269075
        with:
          args: '*.bin'
```
Output:
```
Arguments : *.bin
Release ID: 
Discovered RELEASE_ID: null
```
#### 👍 `@master` with releaseId: 28269075

Used this:
```yml
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.bin'
          releaseId: ${{ steps.create_release.outputs.id }}
```
Output:
```
Arguments : *.bin
Release ID: 28269075
Using supplied RELEASE_ID: 28269075
```
#### 👍  `@master` with releaseId: `${{ steps.create_release.outputs.id }}`
Used this:
```yml
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.bin'
          releaseId: ${{ steps.create_release.outputs.id }}
```
Output:
```
Arguments : *.bin
Release ID: 28269075
Using supplied RELEASE_ID: 28269075
```
The last one is what I have started with but that was not on `@master`. 
So tested again with `@release-1.3` to verify:
#### 👎 `@release-1.3` with releaseId: `${{ steps.create_release.outputs.id }}`
Used this:
```yml
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.bin'
          releaseId: ${{ steps.create_release.outputs.id }}
```
Output:
```
Processing file esp8266_logger-0.2.5.bin
Upload URL is https://uploads.github.com/repos/No3x/pio-release-nofuss-test/releases/null/assets?name=esp8266_logger-0.2.5.bin
***************************
 upload was not successful.
 Aborting
 HTTP status is 404
**********************************
{"message":"Not Found","request_id":"0400:11D5:6D1C:9473:5F048FAF","documentation_url":"https://developer.github.com/v3"}
```
#### 👍 tl;dr:  `@master` with releaseId: `${{ steps.create_release.outputs.id }}`
Use
```yml
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.bin'
          releaseId: ${{ steps.create_release.outputs.id }}
```

Thanks for your support
