### ISSUE TITLE
upload was not successful - 401 Bad Credentials

### ISSUE THREAD

**Issue by tommasodargenio** [skx/github-action-publish-binaries#24]
I'm new to the GitHub actions and I'm trying to set up a workflow where upon creating a new release my .NET console application is built and the executables published. I come across your actions which seem to be doing exactly what I need but I'm having some issues.

the workflow is triggered on release, and there is a previous build job which creates the exes (this is running on a Windows host), and upload the artefacts to a working directory (here is env.PUBLISH_PATH_LIN).

after the build job (called generate) is finished, the following deploy job runs. Where I download the artefacts to the working directory (since I'm changing runner I couldn't access these from the previous jobs), I can confirm the files are in the working directory (I've used an ls -al step to verify). Though the github-action-publish-binaries fails with the error shown below.

Any idea of how to solve/troubleshoot?
```
deploy:
    runs-on: ubuntu-latest
    needs: [generate]
    steps:
    - name: Download the build artifact
      uses: actions/download-artifact@v2
      with:
        name: wallpaperbuddy
        path: '${{env.PUBLISH_PATH_LIN}}'            
    - name: Verify download
      run: ls -al '${{env.PUBLISH_PATH_LIN}}' 
    - name: Upload the Artifacts to Release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: $ {{ secrets.GITHUB_TOKEN }}            
      with:
        args: '${{env.PUBLISH_PATH_LIN}}/*.*'
```

**ERROR**

 upload was not successful.
 Aborting
 HTTP status is 401
**********************************
{"message":"Bad credentials","request_id":"0400:09FA:14B9:81D1:5F33F829","documentation_url":"https://docs.github.com/rest"}
