### ISSUE TITLE
failed upload with 404 status

### ISSUE THREAD

**Issue by vkuznet** [skx/github-action-publish-binaries#25]
Hi,
I'm new to action and wanted to combine your action to upload compiled binaries of my code. I used this [file](https://github.com/dmwm/dasgoclient/blob/master/.github/workflows/release.yml), and upon execution I got the following error:
```
Run skx/github-action-publish-binaries@master
  with:
    args: dasgoclient_*
  env:
    GOROOT: /opt/hostedtoolcache/go/1.15.4/x64
    GITHUB_TOKEN: ***
/usr/bin/docker run --name bb1075efeca57b8c4f70809257b2cc39b030_5cd7aa --label 54bb10 --workdir /github/workspace --rm -e GOROOT -e GITHUB_TOKEN -e INPUT_RELEASEID -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/dasgoclient/dasgoclient":"/github/workspace" 54bb10:75efeca57b8c4f70809257b2cc39b030  "dasgoclient_*" ""
Arguments : dasgoclient_*
Release ID: 
Discovered RELEASE_ID: null
Processing file dasgoclient_arm
Upload URL is https://uploads.github.com/repos/dmwm/dasgoclient/releases/null/assets?name=dasgoclient_arm
***************************
 upload was not successful.
 Aborting
 HTTP status is 404
**********************************
{"message":"Not Found","request_id":"07C0:69DD:2A5680:30FDC2:5FAD4577","documentation_url":"https://docs.github.com/rest"}
```

From this message I see two potential problems:
- I don't see that release ID was found
- I don't know if uploads.github.com URL is actually accessible

Could you please provide a guidance how to fix this issue.
Thanks,
Valentin.

**Comment by skx** [comment]
The action only uploads binaries to a release.  You're passing a "releaseId", but that's only something you need to do if you're actually _creating_ a release, and uploading as part of the same workflow.

Since your workflow is actually triggered by the creation of a release ( due to `on: release:`) you can drop that, and it should "just work":

```
name: Release

on:
  release:
    types: [created]
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get github.com/dmwm/cmsauth
        go get github.com/dmwm/das2go
        go get github.com/vkuznet/x509proxy
        go get github.com/buger/jsonparser
        go get github.com/pkg/profile
        go get github.com/stretchr/testify
    - name: Build
      run: |
        GOARCH=amd64 GOOS=windows go build -ldflags="-s -w -extldflags -static" -o dasgoclient.exe
        GOOS=darwin go build -ldflags="-s -w -extldflags -static" -o dasgoclient_osx
        GOARCH=ppc64le GOOS=linux go build -ldflags="-s -w -extldflags -static" -o dasgoclient_ppc
        GOARCH=arm64 GOOS=linux go build -ldflags="-s -w -extldflags -static" -o dasgoclient_arm
        GOOS=linux go build -ldflags="-s -w -extldflags -static" -o dasgoclient_linux
    - name: Upload binaries
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'dasgoclient_*'
```
