### ISSUE TITLE
Artifact doesn't exist when it does?

### ISSUE THREAD

**Issue by jwvanderbeck** [skx/github-action-publish-binaries#29]
I've been beating my head against the wall on this all day today and I don't know what I am doing wrong.

I build the project, copy some files, and zip them up in steps before this one.  Then I call this one with the path to the ZIP file that should be added to the release.

Yet it always tells me the artifact doesn't exist, despite it clearly being there.  I even used `ls` to output the files after zipping them to verify, yes, the zip file is there as expected.

I'm wondering if there is some cross docker barrier or something I am running into? I don't know anything about docker :(

You can see a run here: https://github.com/KSP-RO/RSSTimeFormatter/runs/2755047394?check_suite_focus=true

Here is one of the failures with the relevant (I think) bits highlighted
![opera_D9vnaU3uEh_LI](https://user-images.githubusercontent.com/161126/120908918-35488700-c624-11eb-895a-4eafdf4e6b88.jpg)

**Comment by jwvanderbeck** [comment]
Workflow is here: https://github.com/KSP-RO/RSSTimeFormatter/blob/8e56327ad74ffbbfb207a9120daaf3d57bd8bb8a/.github/workflows/release-created.yml

**Comment by skx** [comment]
I've not had this issue myself, but it does make me wonder if the different steps are running in new containers without shared state.

I've certainly seen people report that, and resort to temporary uploads/downloads for example:

* https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs

I guess the simplest way to test would be to add a step between your zip and upload actions.  Something like:

```
      - name: Assemble release
        id: assemble-release
        run: |
          RELEASE_DIR="${RUNNER_TEMP}/release"
          echo "Release dir: ${RELEASE_DIR}"
          echo "Release zip: ${RELEASE_DIR}/RSSDateTime-${{ github.event.release.tag_name }}.zip"
          mkdir -v "${RELEASE_DIR}"
          echo "::set-output name=release-dir::${RELEASE_DIR}"
          cp -v -R "${GITHUB_WORKSPACE}/GameData" "${RELEASE_DIR}"
          zip ${RELEASE_DIR}/RSSDateTime-${{ github.event.release.tag_name }}.zip ${RUNNER_TEMP}/release/GameData ${RUNNER_TEMP}/release/GameData/RSSDateTime/* ${RUNNER_TEMP}/release/GameData/RSSDateTime/Plugins/RSSTimeFormatter.dll
          ls -lrt -d -1 "${RELEASE_DIR}"/{*,.*}

      - name: sanity-check
        id: assemble-release-check
        run: |
          echo "Release:"
          ls -R /home/runner/work/_temp/release
          echo "Workspace"
          ls -R /home/runner/work/
          echo "Runner"
          ls -R /home/runner/

      - name: release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ steps.assemble-release.outputs.release-dir }}/RSSDateTime-${{ github.event.release.tag_name }}.zip        
```


(The way I do things is to add a ".github/build" script to do the build, then just run the two actions after each other.  e.g:

```
on: release
name: Handle Release
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Generate the artifacts
      uses: skx/github-action-build@master
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: rss2email-*
```

That always seems to work, with the second step running ".githhub/build" and the third step uploading the result.   Sample https://github.com/skx/rss2email/tree/master/.github
