### ISSUE TITLE
Error: Malformed request

### ISSUE THREAD

**Issue by Jeff-Tian** [skx/github-action-publish-binaries#5]
Hello, thanks for your great action!

I met the following error when I use it in my **private** repo. Could you please help investigate where is wrong?

```
upload artifacts1s

Run skx/github-action-publish-binaries@master
  with:
    args: main.pdf
  env:
    GITHUB_TOKEN: ***

Processing file main.pdf
https://uploads.github.com/repos/Jeff-Tian/thesis/releases/20606245/assets?name=main.pdf
<!DOCTYPE html><title>Malformed request</title>
<body>We didn't receive a proper request from your browser. Please contact us if the problem persists.</body>
</html>
```

**Comment by skx** [comment]
That's a really weird one.  I'll try to reproduce over the weekend, with a test-repository.

If you have the chance it might be worth seeing if you have the same problem with a public-repository, as that it something I've never tested.

I assume that your workflow file looks something like this:

```
on: release
name: Handle Release
jobs:
  upload:
    name: Upload release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: *.pdf
```

That _should_ be enough to make things work.  The only failure-case I've seen so far is if an artifact is zero-bytes in length, that triggers an errors during the upload of "Content-size: unknown", or similar.  But that doesn't seem to be what you're seeing here.

**Comment by skx** [comment]
I made a repository, and even a private repository, but cannot reproduce this.

More details would be helpful, but we've made a couple of new releases with better output.  Perhaps that will be helpful?

**Comment by Jeff-Tian** [comment]
I tried again still failed, but I see the improvements, now the 400 will fail the action, which makes more sense:

```
Upload artifacts2s
##[error]Docker run failed with exit code 1
Run skx/github-action-publish-binaries@master
/usr/bin/docker run --name e959fb98be83a09360482db67d2b1a4c3c8349_f2d1d2 --label e959fb --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/thesis/thesis":"/github/workspace" e959fb:98be83a09360482db67d2b1a4c3c8349 *.pdf
Processing file main.pdf
Upload URL is https://uploads.github.com/repos/Jeff-Tian/thesis/releases/20830841/assets?name=main.pdf
***************************
 upload was not successful.
 Aborting
 HTTP status is 400
**********************************
<!DOCTYPE html><title>Malformed request</title>
<body>We didn't receive a proper request from your browser. Please contact us if the problem persists.</body>
</html>
##[error]Docker run failed with exit code 1
```

Is it related to the token? Can you share more detail about creating the GITHUB_TOKEN?

Here is my configuration:

```
      - name: Upload artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "*.pdf"
```
